---
title: "Proyecto final Series de Tiempo 2025 Otoño Invierno"
format: 
  revealjs:
    scrollable: true
    incremental: true
    smaller: true
    theme: default
    embed-resources: true
execute:
  echo: true
  output-location: column-fragment
---

```{r}
#| echo: false
#| warning: false
#| message: false

library(tidyquant)
library(tidyverse)
library(tsibble)
library(fable)
library(fabletools)
library(feasts)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(glue)
library(ggtime)
library(plotly)
```

##Tienda Delicatessen
Vende principalmente **embutidos** (**carnes frías**) y **quesos** y productos derivados de ello (charolas de carnes frías/quesos, baguettes, etc.).


Tiene horario de lunes a viernes de 10:00 a 19:00 horas y sábados de 10:00 a 15:00 horas (cerrada los domingos).

```{r}
load("C:/Users/hecto/OneDrive - ITESO/Series de tiempo/Series-de-tiempo/proyecto_final.RData")
datos_tsb
```


```{r}
ventas_hora_plt <- datos_tsb |>
  ggplot(aes(x = fecha, y = total)) +
  geom_line()
```


```{r}
ventas_tienda <- datos_tsb |>
  mutate(
    hour = floor_date(fecha, unit = "hour")  # por si hubiera minutos/segundos
  ) |>
  index_by(hour) |>
  summarise(
    total = sum(total)   # ventas totales por hora
  ) |>
  mutate(
    day_type = case_when(
      wday(hour, week_start = 1) %in% c(6, 7) ~ "Weekend",
      TRUE ~ "Weekday"
    ),
    work_day = day_type == "Weekday"
  )
```



```{r}
p_ventas <- ventas_tienda |>
  autoplot(total) +
  labs(
    title = "Ventas por hora de la tienda",
    x = "Fecha y hora",
    y = "Total"
  )

p_ventas_int <- ggplotly(p_ventas, dynamicTicks = TRUE) |>
  rangeslider()   # de plotly

p_ventas_int
```


```{r}
library(fpp3)
library(plotly)
library(fable.prophet)

# 1) Agregar por hora (por si hay varios folios en la misma hora)
ventas_tienda <- datos_tsb |>
  mutate(
    hour = lubridate::floor_date(fecha, unit = "hour")
  ) |>
  index_by(hour) |>
  summarise(
    total = sum(total)
  ) |>
  mutate(
    day_type = dplyr::case_when(
      lubridate::wday(hour, week_start = 1) %in% c(6, 7) ~ "Weekend",
      TRUE ~ "Weekday"
    ),
    work_day = day_type == "Weekday"
  )

# 2) (opcional) entrenamiento = todo lo observado
ventas_tienda_train <- ventas_tienda

# 3) Horizonte: horas hasta el último día de noviembre 2025
last_obs   <- max(ventas_tienda$hour)
target_end <- lubridate::ymd_h("2025-11-30 23")

h_ventas <- as.numeric(
  difftime(target_end, last_obs, units = "hours")
)

h_ventas   # número de pasos a pronosticar

```



```{r}
# 1.1 Descomposición STL (puedes hacerla más elaborada si quieres)
ventas_stl <- ventas_tienda_train |>
  model(
    stl = STL(
      total ~ season(window = "periodic")
    )
  )

# 1.2 Generar réplicas bootstrap (block bootstrap)
ventas_sim <- ventas_stl |>
  generate(
    new_data = ventas_tienda_train,
    times = 100,                 # réplicas bootstrap
    bootstrap_block_size = 24*7  # bloque = 1 semana
  ) |>
  select(-.model, -total)

# 1.3 ETS sobre cada réplica y pronósticos hasta noviembre 2025
#ventas_ets_boot_fc <- ventas_sim |>
  #model(ets = ETS(.sim)) |>
  #forecast(h = h_ventas)



```



```{r}
ventas_tienda_fit <- ventas_tienda_train |>
  model(

     #6) Prophet
    prophet = prophet(
      total ~ growth("linear") +
        season("week") +
        season("year")
    ),

  )

ventas_tienda_fit |>
  report()

```



```{r}
ventas_tienda_fc <- ventas_tienda_fit |>
  forecast(h = h_ventas)

```



```{r}
p_fc_ventas <- ventas_tienda_fc |>
  autoplot(ventas_tienda) +
  autolayer(ventas_bagged_fc, bagged_mean, colour = "red") +
  labs(
    title = "Pronósticos de ventas por hora hasta Noviembre 2025",
    y = "Total",
    x = "Fecha y hora"
  )

p_fc_ventas

```



```{r}
p_fc_ventas_int <- p_fc_ventas |>
  ggplotly(dynamicTicks = TRUE) |>
  layout(
    xaxis = list(
      rangeslider = list(visible = TRUE)
    )
  )

p_fc_ventas_int

```




```{r}
# Accuracy en entrenamiento
ventas_acc_train <- ventas_tienda_fit |>
  accuracy()

ventas_acc_train |>
  select(.model, MAPE) |>
  arrange(MAPE)

# Accuracy en todo el periodo conocido usando los pronósticos (tipo test),
# si defines explícitamente un conjunto de test.

```






























































